name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Development_Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
  Development_Deployment:
    runs-on: ubuntu-latest
    needs: Development_Build
    env:
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_KEY: ${{ secrets.SSH_KEY }}      
    steps:
      - name: Configure SSH Settings
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/testing.key
          chmod 600 ~/.ssh/testing.key
          cat >> ~/.ssh/config <<END
          Host test-node
            HostName $SSH_HOST
            User $SSH_USER
            Port 22
            IdentityFile ~/.ssh/testing.key
            StrictHostkeyChecking no
          END
      - name: Deployment
        run: |
          ssh test-node /bin/bash <<EOF
            cd /var/www/Octopus
            export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
            pm2 stop octopusApp
            git pull
            pm2 stop octopusApp 
            npm install
            pm2 start octopus.js --name octopusApp
          EOF
