# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Configure SSH Settings
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/testing.key
        chmod 600 ~/.ssh/testing.key
        cat >> ~/.ssh/config <<END
        Host test-node
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/testing.key
          StrictHostkeyChecking no
        END
#     - name: SSH Remote Commands
#       uses: appleboy/ssh-action@v0.1.8
#       with:
#         key: ${{secrets.VM_PASS}}
#         host: ${{secrets.VM_IP}}
#         username: ${{secrets.VM_USER_NAME}}
#         port: 54321
#         script: |
#           cd /var/www/Octopus
#           pm2 stop octopusApp
#           git pull
#           npm install
#           pm2 start octopus.js --name octopusApp
